apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mpq1990-com-tls
spec:
  secret: mpq1990-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mpq1990.com
  dnsNames:
    - mpq1990.com
    - www.mpq1990.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mpq1990.com
          - www.mpq1990.com
